import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
  Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  records_sidebar: [
    {
      type: 'category',
      label: 'Operating Systems Lab',
      items: [
        {type: 'autogenerated', dirName: 'records/os'},
      ],
    },
    {
      type: 'category',
      label: 'Database Management Lab',
      items: [
        {type: 'autogenerated', dirName: 'records/dbms'},
      ]
    },
    /**
    
    */
  ],
  /**
  guides_sidebar: [
    'index',
    {
      type: 'category',
      label: 'Operating Systems',
      items: [{type: 'autogenerated', dirName: 'guides'}],
    }
  ],
  */

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
